apiVersion: v1
kind: Secret
metadata:
  name: hubflow-secrets
  namespace: hubflow
type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_PASSWORD: hubflow_pass
  JWT_SECRET: hubflow_prod_secret_jwt_key_2026